blank_issues_enabled: true
contact_links:
  - name: Ask a question, give feedback, share your project
    url: https://github.com/mantinedev/mantine/discussions
    about: Connect with other community members with Github discussions
  - name: Sign up for updates newsletter
    url: https://buttondown.email/mantine
    about: Receive monthly Mantine updates in your mail
